### ISSUE TITLE
notification center

### ISSUE THREAD

**Issue by raynor84** [cliffparnitzky/FormExternalForwarding#3]
I have the plugin notification center installed. When I use this extension it forwards the page correctly to an external site. But no Mail gets send from the notification center.

**Comment by cliffparnitzky** [comment]
Hi, yeah, that ist correct. This extension only offers the possibility to change the `action` attribute of the HTML Form. When submitting the form, no Contao hook or other code will be involved. The browser directly forwards you to the external page.

If you want to have email sending and external forwarding I recommand a custom hook implementation.

**Comment by raynor84** [comment]
I thought you are using some contao-hook from what I saw from the code (e.g. ProcessFormData). When I add requires[]="notification_center" to the autoload.ini it works. But maybe there is a better way to do it. E.g. with the new Contao-Bundle where setLoadAfter Notification_center is set. Or some other method.

**Comment by cliffparnitzky** [comment]
Oh sorry, you are right. Sometimes it is better to check the own code.

The `processFormData` hook prepares the external URL and redirects the use. The reason, why the `notification_center` mail is not send, is the order of teh hook execution.

When adding `requires[]="notification_center"` to the `autoload.ini` you ensure, the `notification_center` hook implemention is added to the list at first and therefore executed first.

This should be solve youre problem. But this is not update save.

**Comment by raynor84** [comment]
is there a way to implement it in the repository?

**Comment by cliffparnitzky** [comment]
No, sorry. I don't want to add this dependency. Because the `autoload.ini` is nothing dynamic, I can't add a switch for checking.
